src/Entity/Contrato.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContratoRepository")
 */
class Contrato
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cliente", inversedBy="contratos")
     */
    private $id_cli;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_con;

    /**
     * @ORM\Column(type="date")
     */
    private $vig_con;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ContratoProducto", mappedBy="id_con")
     */
    private $contratoProductos;

    public function __construct()
    {
        $this->contratoProductos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCli(): ?Cliente
    {
        return $this->id_cli;
    }

    public function setIdCli(?Cliente $id_cli): self
    {
        $this->id_cli = $id_cli;

        return $this;
    }

    public function getNumCon(): ?int
    {
        return $this->num_con;
    }

    public function setNumCon(int $num_con): self
    {
        $this->num_con = $num_con;

        return $this;
    }

    public function getVigCon(): ?\DateTimeInterface
    {
        return $this->vig_con;
    }

    public function setVigCon(\DateTimeInterface $vig_con): self
    {
        $this->vig_con = $vig_con;

        return $this;
    }

    /**
     * @return Collection|ContratoProducto[]
     */
    public function getContratoProductos(): Collection
    {
        return $this->contratoProductos;
    }

    public function addContratoProducto(ContratoProducto $contratoProducto): self
    {
        if (!$this->contratoProductos->contains($contratoProducto)) {
            $this->contratoProductos[] = $contratoProducto;
            $contratoProducto->setIdCon($this);
        }

        return $this;
    }

    public function removeContratoProducto(ContratoProducto $contratoProducto): self
    {
        if ($this->contratoProductos->contains($contratoProducto)) {
            $this->contratoProductos->removeElement($contratoProducto);
            // set the owning side to null (unless already changed)
            if ($contratoProducto->getIdCon() === $this) {
                $contratoProducto->setIdCon(null);
            }
        }

        return $this;
    }
}

src/Form/ContratoType.php
<?php

namespace App\Form;

use App\Entity\Contrato;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContratoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('num_con')
            ->add('vig_con')
            ->add('id_cli')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contrato::class,
        ]);
    }
}

src/Controller/ContratoController.php
<?php

namespace App\Controller;

use App\Entity\Contrato;
use App\Form\ContratoType;
use App\Repository\ContratoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contrato")
 */
class ContratoController extends AbstractController
{
    /**
     * @Route("/", name="contrato_index", methods={"GET"})
     */
    public function index(ContratoRepository $contratoRepository): Response
    {
        return $this->render('contrato/index.html.twig', [
            'contratos' => $contratoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="contrato_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $contrato = new Contrato();
        $form = $this->createForm(ContratoType::class, $contrato);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contrato);
            $entityManager->flush();

            return $this->redirectToRoute('contrato_index');
        }

        return $this->render('contrato/new.html.twig', [
            'contrato' => $contrato,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contrato_show", methods={"GET"})
     */
    public function show(Contrato $contrato): Response
    {
        return $this->render('contrato/show.html.twig', [
            'contrato' => $contrato,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="contrato_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Contrato $contrato): Response
    {
        $form = $this->createForm(ContratoType::class, $contrato);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('contrato_index');
        }

        return $this->render('contrato/edit.html.twig', [
            'contrato' => $contrato,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contrato_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Contrato $contrato): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contrato->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($contrato);
            $entityManager->flush();
        }

        return $this->redirectToRoute('contrato_index');
    }
}

templates/contrato/_delete_form.html.twig
<form method="post" action="{{ path('contrato_delete', {'id': contrato.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrato.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contrato/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contrato/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contrato{% endblock %}

{% block body %}
    <h1>Edit Contrato</h1>

    {{ include('contrato/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('contrato_index') }}">back to list</a>

    {{ include('contrato/_delete_form.html.twig') }}
{% endblock %}

templates/contrato/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrato index{% endblock %}

{% block body %}
    <h1>Contrato index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num_con</th>
                <th>Vig_con</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contrato in contratos %}
            <tr>
                <td>{{ contrato.id }}</td>
                <td>{{ contrato.numCon }}</td>
                <td>{{ contrato.vigCon ? contrato.vigCon|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('contrato_show', {'id': contrato.id}) }}">show</a>
                    <a href="{{ path('contrato_edit', {'id': contrato.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('contrato_new') }}">Create new</a>
{% endblock %}

templates/contrato/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contrato{% endblock %}

{% block body %}
    <h1>Create new Contrato</h1>

    {{ include('contrato/_form.html.twig') }}

    <a href="{{ path('contrato_index') }}">back to list</a>
{% endblock %}

templates/contrato/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contrato{% endblock %}

{% block body %}
    <h1>Contrato</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contrato.id }}</td>
            </tr>
            <tr>
                <th>Num_con</th>
                <td>{{ contrato.numCon }}</td>
            </tr>
            <tr>
                <th>Vig_con</th>
                <td>{{ contrato.vigCon ? contrato.vigCon|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('contrato_index') }}">back to list</a>

    <a href="{{ path('contrato_edit', {'id': contrato.id}) }}">edit</a>

    {{ include('contrato/_delete_form.html.twig') }}
{% endblock %}