src/Entity/Pedido.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PedidoRepository")
 */
class Pedido
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $fec_ped;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cliente", inversedBy="pedidos")
     */
    private $id_cli;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $est_ped;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PedidoProducto", mappedBy="id_ped")
     */
    private $pedidoProductos;

    public function __construct()
    {
        $this->pedidoProductos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecPed(): ?\DateTimeInterface
    {
        return $this->fec_ped;
    }

    public function setFecPed(\DateTimeInterface $fec_ped): self
    {
        $this->fec_ped = $fec_ped;

        return $this;
    }

    public function getIdCli(): ?Cliente
    {
        return $this->id_cli;
    }

    public function setIdCli(?Cliente $id_cli): self
    {
        $this->id_cli = $id_cli;

        return $this;
    }

    public function getEstPed(): ?string
    {
        return $this->est_ped;
    }

    public function setEstPed(string $est_ped): self
    {
        $this->est_ped = $est_ped;

        return $this;
    }

    /**
     * @return Collection|PedidoProducto[]
     */
    public function getPedidoProductos(): Collection
    {
        return $this->pedidoProductos;
    }

    public function addPedidoProducto(PedidoProducto $pedidoProducto): self
    {
        if (!$this->pedidoProductos->contains($pedidoProducto)) {
            $this->pedidoProductos[] = $pedidoProducto;
            $pedidoProducto->setIdPed($this);
        }

        return $this;
    }

    public function removePedidoProducto(PedidoProducto $pedidoProducto): self
    {
        if ($this->pedidoProductos->contains($pedidoProducto)) {
            $this->pedidoProductos->removeElement($pedidoProducto);
            // set the owning side to null (unless already changed)
            if ($pedidoProducto->getIdPed() === $this) {
                $pedidoProducto->setIdPed(null);
            }
        }

        return $this;
    }
}

src/Form/PedidoType.php
<?php

namespace App\Form;

use App\Entity\Pedido;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


use App\Entity\Cliente;

class PedidoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fec_ped')
            ->add('est_ped')
            ->add('id_cli', EntityType::class,[
                'class' => Cliente::class,
                'choice_label'=>'nom_cli'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pedido::class,
        ]);
    }
}

src/Controller/PedidoController.php
<?php

namespace App\Controller;

use App\Entity\Pedido;
use App\Entity\Cliente;
use App\Entity\Contrato;

use App\Form\PedidoType;

use App\Repository\PedidoRepository;
use App\Repository\ContratoRepository;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pedido")
 */
class PedidoController extends AbstractController
{
    /**
     * @Route("/", name="pedido_index", methods={"GET"})
     */
    public function index(PedidoRepository $pedidoRepository, ContratoRepository $contratoRepository): Response
    {
        return $this->render('pedido/index.html.twig', [
            'pedidos' => $pedidoRepository->findAll(),
            'contratos' => $contratoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pedido_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pedido = new Pedido();
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pedido);
            $entityManager->flush();

            return $this->redirectToRoute('pedido_index');
        }

        return $this->render('pedido/new.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedido_show", methods={"GET"})
     */
    public function show(Pedido $pedido): Response
    {
        return $this->render('pedido/show.html.twig', [
            'pedido' => $pedido,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pedido_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pedido $pedido): Response
    {
        $form = $this->createForm(PedidoType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pedido_index');
        }

        return $this->render('pedido/edit.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedido_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Pedido $pedido): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pedido->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pedido);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pedido_index');
    }
}

templates/pedido/_delete_form.html.twig
<form method="post" action="{{ path('pedido_delete', {'id': pedido.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pedido.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pedido/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pedido/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pedido{% endblock %}

{% block body %}
    <h1>Edit Pedido</h1>

    {{ include('pedido/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pedido_index') }}">back to list</a>

    {{ include('pedido/_delete_form.html.twig') }}
{% endblock %}

templates/pedido/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido index{% endblock %}

{% block body %}

    {% set cont = 0 %}

    <h1>Lista de pedidos pendientes</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fecha</th>
                <th>Cliente</th>
                <th>Contrato</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
            {% if pedido.estPed == "P" %}
            <tr>
                {# {% set  %} #}
                <td>{{ pedido.id }}</td>
                <td>{{ pedido.fecPed ? pedido.fecPed|date('Y-m-d') : '' }}</td>
                <td> {{ pedido.getIdCli().getNomCli() }} </td>
                <td> <a href= " {{ path('contrato_show',  {'id': pedido.id}) }} " >Ver contrato</a> </td>

                {# <td> {{ pedido.getIdCli() }} </td> #}
                <td>
                    <a href="{{ path('pedido_show', {'id': pedido.id}) }}">show</a>
                    <a href="{{ path('pedido_edit', {'id': pedido.id}) }}">edit</a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pedido_new') }}">Create new</a>
{% endblock %}

templates/pedido/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pedido{% endblock %}

{% block body %}
    <h1>Create new Pedido</h1>

    {{ include('pedido/_form.html.twig') }}

    <a href="{{ path('pedido_index') }}">back to list</a>
{% endblock %}

templates/pedido/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedido{% endblock %}

{% block body %}
    <h1>Pedido</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pedido.id }}</td>
            </tr>
            <tr>
                <th>Fec_ped</th>
                <td>{{ pedido.fecPed ? pedido.fecPed|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Est_ped</th>
                <td>{{ pedido.estPed }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pedido_index') }}">back to list</a>

    <a href="{{ path('pedido_edit', {'id': pedido.id}) }}">edit</a>

    {{ include('pedido/_delete_form.html.twig') }}
{% endblock %}